name: Pylint Error Report
description: Report a PyLint linting issue to help us improve Python code quality
labels: ["lint", "bug", "pylint"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a PyLint issue. Please provide as much detail as possible so we can investigate and improve the linting rules or codebase.

  - type: textarea
    id: github-action-workflow
    attributes:
      label: Link to GitHub Action Workflow
      description: If this linting error was detected in a GitHub Action, please provide the link to the workflow run.
      placeholder: |
        www.github.com/your-repo/actions/runs/1234567890
    validations:
      required: true

  - type: textarea
    id: brief-description
    attributes:
      label: Breif Description
      description: How would you describe the linting issue?
      placeholder: |
        The code has an unused import statement.
        The variable name is too short.
    validations:
      required: true


  - type: markdown
    attributes:
      value: |
        ---
        By submitting this issue, you agree to follow our [Code of Conduct](../CODE_OF_CONDUCT.md).
