name: Run Linter

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Set up Python virtual environment
        run: |
          cd api
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint

      - name: Run pylint
        run: |
          source venv/bin/activate
          pylint $(git ls-files '*.py')
